In [1]:
#1
import numpy as np

In [5]:
# 2
print(np.version) # 打印的是路径
print(np.__version__) # 打印的才是版本
np.show_config() # 配置说明

<module 'numpy.version' from 'C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>
1.16.2
openblas_lapack_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]
openblas_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
blas_opt_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE


In [4]:
# 3
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# 4
z = np.zeros(10)
print(z)
print(z.size) # size 大小
print(z.itemsize) #输出元素的字节数
print(z.size*z.itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10
8
80


In [7]:
# 5
import numpy
np.info(np.add) 
numpy.info(numpy.add) # 非常重要，对于查看函数的属性

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
# 6
z = np.zeros(10)
print(z)
z[4]=1
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# 7
z = np.arange(10,50,2)
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [21]:
# 8
z=z[::-1]
print(z)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [24]:
# 9
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# 10
z = np.array([1,2,0,0,4,0])
index1 = np.nonzero(z)
index1


(array([0, 1, 4], dtype=int64),)

In [29]:
# 11
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
z = np.random.randn(27).reshape(3,3,3)
print(z)
z = np.random.random((3,3,3))
print(z)

[[[-1.04887965 -0.10160876 -0.97878244]
  [-1.74185888  0.36320114  0.838537  ]
  [ 0.1239353   1.17138618  0.08983334]]

 [[ 0.11327724  0.61910773  0.61269968]
  [-1.0715255   1.24327034  0.09960049]
  [ 0.18006868 -0.4618413   1.24143797]]

 [[ 1.21100649  0.24524586 -0.25551848]
  [ 0.24529508 -0.69290976 -0.11146581]
  [-0.73998167  0.6540039   0.65306116]]]
[[[0.57154855 0.00156137 0.62480061]
  [0.39570423 0.50608836 0.24875173]
  [0.28233993 0.80612213 0.07300757]]

 [[0.65621572 0.71212161 0.76930708]
  [0.49653133 0.18509598 0.40325239]
  [0.69297921 0.53606215 0.94233845]]

 [[0.19402167 0.09846662 0.20396635]
  [0.76421198 0.23351886 0.35346248]
  [0.86681232 0.1828243  0.02342453]]]


In [34]:
z = np.random.random((10,10))
print(z)
print(z.max())
print(z.min())

[[9.04553463e-01 9.04023100e-01 6.98185982e-01 8.29335247e-01
  7.60089341e-01 2.41505345e-01 7.29479196e-01 9.90873608e-01
  5.46266293e-01 4.48764250e-01]
 [4.36646323e-01 1.71082690e-01 7.55815663e-01 9.30540523e-01
  6.28146384e-01 1.60048745e-01 6.23434313e-01 1.69338737e-01
  8.13569543e-02 7.33784111e-01]
 [1.33235840e-01 1.11169451e-01 1.80813133e-01 3.24723604e-01
  8.14094999e-01 2.00109783e-01 4.21499998e-02 1.32469815e-02
  9.75319691e-01 9.99526346e-01]
 [9.94494439e-01 2.57334284e-01 1.61074096e-01 3.89874182e-01
  6.45041459e-01 2.91049093e-01 8.42717564e-01 6.67453095e-01
  4.56160437e-01 5.68735332e-01]
 [3.10954692e-01 5.09613912e-02 7.38865940e-01 1.19989177e-02
  8.11665255e-01 1.59024557e-01 3.56226107e-01 2.95238095e-01
  1.10354204e-02 9.07780457e-01]
 [3.48789509e-01 3.16866139e-01 3.25137548e-01 9.02714552e-01
  2.82843131e-01 5.81182105e-01 1.21130159e-01 4.74606805e-01
  8.77560012e-01 3.16149029e-02]
 [7.66638803e-01 4.40945573e-01 7.96369806e-01 1.69428588e

In [36]:
z = np.random.random(30)
np.mean(z)

0.5625708239856639

In [39]:
z = np.ones((4,4))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [41]:
z = np.ones((4,4))
z = np.pad(z,pad_width=1,mode='constant',constant_values=0)
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


In [51]:
z = np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [59]:
z = np.zeros((8,8),dtype=int)
z[1::2,0::2]=1
z[0::2,1::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [62]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [64]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [66]:
z = np.random.random((5,5))
print(z)
print((z-z.min())/(z.max()-z.min()))

[[0.31751241 0.57179998 0.10857945 0.98555763 0.25448672]
 [0.67124638 0.710721   0.51421257 0.39230074 0.36524312]
 [0.26057387 0.15018732 0.92117691 0.74936188 0.41251483]
 [0.71831678 0.66305306 0.99381862 0.54693157 0.15995088]
 [0.9355818  0.16658867 0.14807735 0.60418575 0.14496111]]
[[0.23601865 0.52327162 0.         0.99066806 0.16482242]
 [0.63561006 0.68020211 0.45821868 0.32050241 0.28993709]
 [0.17169871 0.04700183 0.91794115 0.72385232 0.34333702]
 [0.68878259 0.62635457 1.         0.4951793  0.05803113]
 [0.93421346 0.06552943 0.04461833 0.55985581 0.04109811]]


In [67]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [68]:
z = np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [71]:
z = np.arange(10)
z[(3<=z)&(z<=8)] *= -1
z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [73]:
# https://stoneboy100200.github.io/2018/08/09/numpy-sum/
print(sum(range(5),-1))

from numpy import *
print(sum(range(5),-1))

10
10


In [82]:
z = np.arange(5)
# print(z)
# print(z**z)
# print(2<<z<<2)
# print(z<-z)
# print(1j*z)
# print(z/1/1)
# z = np.arange(5)
z < z > z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [83]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


In [85]:
z = np.random.uniform(-10,+10,10)
print(z)
print(np.copysign(np.ceil(np.abs(z)),z))

[ 8.45732668 -4.49091695  3.27061097 -6.03750575  6.37159718  5.34706073
 -0.83774431  9.51796336  1.9510514   8.45224445]
[ 9. -5.  4. -7.  7.  6. -1. 10.  2.  9.]


In [87]:
z1 = np.random.randint(0,10,10)
print(z1)
z2 = np.random.randint(0,10,10)
print(z2)
print(np.intersect1d(z1,z2))

[1 1 6 2 7 6 0 4 4 3]
[2 7 1 3 7 5 5 6 1 4]
[1 2 3 4 6 7]


In [93]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# # Back to sanity
_ = np.seterr(**defaults)

# # An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [4]:
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in sqrt
  from ipykernel import kernelapp as app


False

In [95]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-20
Today is 2019-06-21
Tomorrow is 2019-06-22


In [5]:
z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [6]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)


array([3., 3., 3.])

In [7]:
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


In [10]:
z = np.random.uniform(0,10,10)
print(z)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[0.80418925 6.67151758 7.65129846 8.6716679  2.0148134  3.5148256
 8.85995966 3.47335856 2.76998536 2.05183101]
[0. 6. 7. 8. 2. 3. 8. 3. 2. 2.]
[0. 6. 7. 8. 2. 3. 8. 3. 2. 2.]
[0. 6. 7. 8. 2. 3. 8. 3. 2. 2.]
[0 6 7 8 2 3 8 3 2 2]
[0. 6. 7. 8. 2. 3. 8. 3. 2. 2.]


In [11]:
z = np.zeros((5,5))
print(z)
z = z+np.arange(5)#广播操作
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
def generate():
    for x in range(10):
        yield x
print(generate())
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

<generator object generate at 0x0000000005305B48>
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
z = np.linspace(0,1,11,endpoint=False)[1:]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [28]:
z = np.random.random(10)
z.sort()
print(z)


[0.05607397 0.06115009 0.22138655 0.22288826 0.2667332  0.27052405
 0.49211713 0.60118188 0.64745072 0.98493616]


In [32]:
import time
z = np.arange(5)
tic = time.time()
for i in range(1000):
    np.add.reduce(z)
toc = time.time()
print(toc-tic)
tic = time.time()
for i in range(1000):
    np.sum(z)
toc = time.time()
print(toc-tic)

0.00500035285949707
0.01000070571899414


In [37]:
A = np.random.randint(0,2,5)
print(A)
B = np.random.randint(0,2,5)
print(B)
print(A == B)
equal = np.allclose(A,B)
print(equal)
print(np.array_equal(A,B))

[1 1 0 0 1]
[1 1 0 1 1]
[ True  True  True False  True]
False
False


In [38]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [39]:
z = np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.10628331 0.27215189 0.7865168  0.94330785 1.17235319 0.76735356
 0.57878029 0.98898692 1.35135876 0.75241876]
[1.04867385 0.03099999 0.44597402 0.24830405 0.66878579 1.39999379
 0.69677943 0.68612272 0.74806516 1.282205  ]


In [40]:
z = np.random.random(10)
print(z)
z[z.argmax()] =1
print(z)

[0.98701656 0.42036392 0.35317587 0.43985601 0.21335826 0.20711901
 0.77957028 0.89991939 0.60122713 0.21024018]
[1.         0.42036392 0.35317587 0.43985601 0.21335826 0.20711901
 0.77957028 0.89991939 0.60122713 0.21024018]


In [42]:
z = np.zeros((5,5), [('x',float),('y',float)])
print(z)
z['x'],z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [43]:
x = np.arange(8)
y = x+0.5
c = 1/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.163637117973


In [44]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
# 49 没懂


In [49]:
z = np.arange(100)
print(z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(z-v)).argmin()
print(index)
print (z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
88.11920128982057
88
88


In [50]:
z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [52]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0], z[:,1])
e = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print (e)
e.size

[[0.         0.77014142 1.0171233  0.30934981 0.75493216 0.97898025
  0.91609298 0.57487248 0.7019559  0.46479445]
 [0.77014142 0.         0.25022254 0.58902985 0.77930292 0.21090578
  0.7366332  0.94875564 0.11915953 0.61163651]
 [1.0171233  0.25022254 0.         0.83611356 0.90005801 0.03981284
  0.7964588  1.13184017 0.34926319 0.80158904]
 [0.30934981 0.58902985 0.83611356 0.         0.88953294 0.79630379
  0.99245372 0.81675624 0.48936573 0.58774483]
 [0.75493216 0.77930292 0.90005801 0.88953294 0.         0.88219587
  0.22206284 0.35670926 0.82708897 0.30426669]
 [0.97898025 0.21090578 0.03981284 0.79630379 0.88219587 0.
  0.78745222 1.10494991 0.30959269 0.7727972 ]
 [0.91609298 0.7366332  0.7964588  0.99245372 0.22206284 0.78745222
  0.         0.5786966  0.81275338 0.45169782]
 [0.57487248 0.94875564 1.13184017 0.81675624 0.35670926 1.10494991
  0.5786966  0.         0.9534253  0.33712569]
 [0.7019559  0.11915953 0.34926319 0.48936573 0.82708897 0.30959269
  0.81275338 0.95342

100

In [54]:
z = np.arange(10,dtype=np.int32)
print(z)
z = z.astype(np.float32,copy=False)
z

[0 1 2 3 4 5 6 7 8 9]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [55]:
#54


In [56]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print (index, value)
for index in np.ndindex(z.shape):
    print (index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [57]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma,mu = 1, 0
g = np.exp(-((d-mu)**2/(2*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [62]:
n = 10
p = 50
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False),1)
print (z)

[[1. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 1. 1. 0. 0. 1. 1.]]


In [69]:
x = np.random.rand(5,10)

mean_x = x.mean(axis=1)

y = x-x.mean(axis=1,keepdims=True)
print(y)

[[ 0.46368124  0.25961031  0.3985741  -0.27133935 -0.30518919 -0.30142789
  -0.09959836 -0.36512071  0.34010729 -0.11929744]
 [ 0.03056752 -0.2626911   0.21232004 -0.15130686 -0.24860424  0.09536425
   0.01652035  0.33321101  0.16104776 -0.18642875]
 [ 0.38999585 -0.29038258  0.26062168  0.0730664   0.34271225  0.16164787
  -0.19832437  0.2419075  -0.38483949 -0.59640511]
 [-0.09054235 -0.25393725 -0.18847435 -0.13571914  0.47442247  0.36662169
  -0.13470961 -0.08098294  0.09547804 -0.05215656]
 [-0.06060338  0.00282265 -0.15347739  0.14551773 -0.05148484  0.0331364
  -0.03823225  0.09137173 -0.31566115  0.34661049]]


In [71]:
z = np.random.randint(0,5,(3,3))
print(z)
print(z[z[:,2].argsort()])

[[1 2 3]
 [0 4 1]
 [2 0 4]]
[[0 4 1]
 [1 2 3]
 [2 0 4]]


In [72]:
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


In [73]:
z = np.random.randint(0,3,(3,10))
b = 0.5
print(z.flat[np.abs(z-b).argmin()])


0


In [74]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [75]:
# 63 
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [77]:
z = np.ones(10)
x = np.random.randint(0,len(z),20)
z = z+np.bincount(x,minlength=len(z))
print(z)
np.add.at(z,x,1)
print(z)

[2. 1. 2. 2. 4. 2. 3. 4. 5. 5.]
[3. 1. 3. 3. 7. 3. 5. 7. 9. 9.]


In [78]:
z = [1,2,3,4,5,6]
x = [1,3,9,3,4,1]
y = np.bincount(z,x)
print (y)


[0. 1. 3. 9. 3. 4. 1.]


In [79]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [82]:
z = np.random.random((4,4))
print(z)
y = z.sum(axis=(-2,-1))
print(y)

[[0.99522623 0.4578449  0.5677333  0.27138663]
 [0.79643672 0.11455756 0.5445263  0.97859113]
 [0.99473303 0.0934023  0.94074736 0.40030563]
 [0.15790317 0.61646539 0.44674476 0.51676408]]
8.893368491080325


In [83]:
z = np.random.uniform(0,1,100)
x = np.random.randint(0,10,100)
import pandas as pd
print(pd.Series(z).groupby(x).mean())

0    0.412345
1    0.490048
2    0.497680
3    0.598474
4    0.454446
5    0.653391
6    0.400081
7    0.570180
8    0.421691
9    0.365449
dtype: float64


In [85]:
z = np.random.uniform(0,1,(5,5))
x = np.random.uniform(0,1,(5,5))
np.diag(np.dot(z,x))

array([1.6776261 , 0.81944802, 2.010156  , 1.54501056, 1.48736675])

In [86]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [2]:
import numpy as np
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [3]:
z = np.arange(25).reshape(5,5)
z[[1,2]]=z[[2,1]]
print(z)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 45) ( 0, 73) ( 1, 83) ( 1, 88) (12, 31) (12, 74) (16, 67) (22, 82)
 (22, 93) (31, 74) (33, 35) (33, 89) (35, 89) (45, 73) (46, 46) (46, 54)
 (49, 67) (49, 71) (59, 78) (59, 85) (67, 67) (67, 71) (69, 84) (69, 97)
 (78, 85) (82, 93) (83, 88) (84, 97)]


In [5]:
c = np.bincount([1,1,2,3,4,4,6])
z = np.repeat(np.arange(len(c)),c)
print(z)

[1 1 2 3 4 4 6]


In [7]:
def moving_average(a,n=3):
    ret = np.cumsum(a,dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n
z = np.arange(20)
print(moving_average(z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [8]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [9]:
z = np.random.randint(0,2,100)
np.logical_not(z,out=z)


array([0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0])

In [10]:
def distance(P0,P1,p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 7.48740334  1.03101274  3.03875684  4.95504141  4.21578529  6.58423492
  6.64694243  1.31905217 10.61809871  4.02939734]


In [11]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.24960839  1.98658697  9.13859997  0.39139816 16.53473125  7.98542364
   4.28531583  7.66649666 12.99377088  9.97222514]
 [12.72924227  6.54131485 12.7497207   1.5042073   6.08350429  0.9088473
   3.26247239 14.02612354  8.4786613   1.69603459]
 [ 5.99005573 10.45855025  6.54490048  7.00647758  3.86974802  3.36823085
   3.34310166 12.64169111  7.25827658  5.1219977 ]
 [ 1.91837723 10.3604174   4.33187931  8.3719311   0.12916477  3.57025929
   6.21143259  9.25818011  3.95052955  8.61907149]
 [ 2.7318587   0.37083321 11.0105769   0.1444491   8.88186254  6.14325819
   1.0796524   0.40889079  5.82649856  5.3936059 ]
 [13.32055589  0.96581781 16.55398697  3.13647424  1.17706525  6.34027237
   6.22489641  8.74129356  3.12987491  3.61501281]
 [ 2.5696953   5.04709433  5.13578551  5.740293    9.0686658   1.2374549
   7.00239277  0.14987007  5.12357856 11.15975405]
 [ 8.09115032  5.92395042 17.92609074  6.75816364 10.22133561 12.61745541
   5.6215565   2.59362142  8.17180866  0.83107336]
 [

In [10]:
# 80#
# z = np.random.randint(0,10,(10,10))
# shape = (5,5)
# fill = 0
# position = (1,1)
# r = np.ones(shape,dtype=z.dtype)*fill
# p = np.array(list(position)).astype(int)
# rs = np.array(list(r.shape)).astype(int)
# zs = np.array(list(z.shape)).astype(int)

# r_start = np.zeros((len(shape),)).astype(int)
# r_stop = np.array(list(shape)).astype(int)
# z_start = (r-rs//2)
# z_stop = (p+rs//2)+rs%2

# r_start = (r_start-np.minimum(z_start,0)).tolist()
# z_start = (np.maximum(z_start,0)).tolist()
# r_stop = np.maximum(r_start,(r_stop-np.maximum(z_stop-zs,0))).tolist()
# z_stop = (np.minimum(z_stop,zs)).tolist()

# r = [slice(start,stop) for start,stop in zip(r_start,r_stop)]
# o = [slice(start,stop) for start,stop in zip(z_start,z_stop)]
# r[z] = z[o]
# print(z)
# print(r)


Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[7 4 6 5 3 8 4 1 0 3]
 [4 2 9 8 7 9 6 6 8 0]
 [7 4 9 5 3 1 5 5 0 6]
 [8 4 6 7 7 4 9 8 7 7]
 [7 9 6 9 5 5 1 5 5 1]
 [9 9 5 4 5 2 7 4 4 0]
 [4 1 7 4 9 7 4 2 0 3]
 [4 1 6 9 9 6 8 6 3 0]
 [1 7 1 8 2 9 6 0 5 1]
 [1 9 2 8 5 9 3 5 7 3]]
[[0 0 0 0 0]
 [0 7 4 6 5]
 [0 4 2 9 8]
 [0 7 4 9 5]
 [0 8 4 6 7]]


C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel\__main__.py:50: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [13]:
z = np.arange(1,15)
x = stride_tricks.as_strided(z,(11,4),(4,4))
print(x)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [14]:
z = np.random.uniform(0,1,(10,10))
u,s,v = np.linalg.svd(z)
rank = np.sum(s>1e-10)
print(rank)

10


In [16]:
z = np.random.randint(0,10,50)
print(z)
print(np.bincount(z).argmax())

[1 7 8 5 9 1 7 3 0 2 6 2 1 4 1 1 6 6 0 8 6 0 4 7 5 2 6 0 2 1 3 1 3 1 7 3 3
 3 9 0 0 6 5 2 4 2 9 8 1 4]
1


In [19]:
z = np.random.randint(0,5,(10,10))
n = 3
i = 1+(z.shape[0]-3) # 1+10-3
j = 1+(z.shape[1]-3) # 1+10-3
x= stride_tricks.as_strided(z, shape=(i, j, n, n), strides=z.strides + z.strides)
print (x)

[[[[4 1 4]
   [3 0 3]
   [1 2 3]]

  [[1 4 3]
   [0 3 1]
   [2 3 4]]

  [[4 3 1]
   [3 1 3]
   [3 4 1]]

  [[3 1 4]
   [1 3 3]
   [4 1 4]]

  [[1 4 2]
   [3 3 3]
   [1 4 4]]

  [[4 2 0]
   [3 3 1]
   [4 4 3]]

  [[2 0 2]
   [3 1 3]
   [4 3 0]]

  [[0 2 1]
   [1 3 2]
   [3 0 0]]]


 [[[3 0 3]
   [1 2 3]
   [1 3 2]]

  [[0 3 1]
   [2 3 4]
   [3 2 3]]

  [[3 1 3]
   [3 4 1]
   [2 3 1]]

  [[1 3 3]
   [4 1 4]
   [3 1 3]]

  [[3 3 3]
   [1 4 4]
   [1 3 2]]

  [[3 3 1]
   [4 4 3]
   [3 2 0]]

  [[3 1 3]
   [4 3 0]
   [2 0 1]]

  [[1 3 2]
   [3 0 0]
   [0 1 4]]]


 [[[1 2 3]
   [1 3 2]
   [3 1 1]]

  [[2 3 4]
   [3 2 3]
   [1 1 3]]

  [[3 4 1]
   [2 3 1]
   [1 3 2]]

  [[4 1 4]
   [3 1 3]
   [3 2 3]]

  [[1 4 4]
   [1 3 2]
   [2 3 2]]

  [[4 4 3]
   [3 2 0]
   [3 2 1]]

  [[4 3 0]
   [2 0 1]
   [2 1 0]]

  [[3 0 0]
   [0 1 4]
   [1 0 0]]]


 [[[1 3 2]
   [3 1 1]
   [4 2 2]]

  [[3 2 3]
   [1 1 3]
   [2 2 3]]

  [[2 3 1]
   [1 3 2]
   [2 3 1]]

  [[3 1 3]
   [3 2 3]
   [3 1 0]]

  [[1 3 2]
   

In [20]:
class Symetric(np.ndarray):
    def __setiem__(self,index,value):
        i,j=index
        super(Symetric,self).__setitem__((i,j),value)
        super(Symetric,self).__setitem__((j,i),value)
def symetric(z):
    return np.asarray(z+z.T-np.diag(z.diagonal())).view(Symetric)
s = symetric(np.random.randint(0,10,(5,5)))
s[2,3] = 42
print(s)

[[ 1 13  6 16  1]
 [13  1 14  8  9]
 [ 6 14  3 42  1]
 [16  8  5  4  8]
 [ 1  9  1  8  4]]


In [21]:
p, n = 10, 20
z = np.ones((p,n,n))
x = np.ones((p,n,1))
s = np.tensordot(z, x, axes=[[0, 2], [0, 1]])
print (s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [25]:
z = np.ones((16,16))
k = 4
x = np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0], k), axis=0),
                                       np.arange(0, z.shape[1], k), axis=1)
print (x)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [26]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])


    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print(z[np.argsort(z)[-n:]])

[9995 9996 9997 9998 9999]


In [28]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [30]:
z = np.array([('Hello',2.5,3),
             ('World',3.6,2)])
x = np.core.records.fromarrays(z.T,names='cols1,col2,col3',formats='S8,f8,i8')
print(x)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [31]:
z = np.random.rand()
np.power(z,3)

0.0036522212630043316

In [32]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))
c = (a[...,np.newaxis,np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[0 3 4 6]


In [33]:
z = np.random.randint(0,5,(10,3))
print(z)
x = np.all(z[:,1:] == z[:,:-1],axis=1)
y = z[~x]
print(y)

[[2 4 3]
 [0 2 0]
 [3 4 2]
 [2 3 2]
 [1 3 3]
 [1 2 4]
 [3 1 3]
 [4 2 3]
 [1 3 0]
 [4 1 0]]
[[2 4 3]
 [0 2 0]
 [3 4 2]
 [2 3 2]
 [1 3 3]
 [1 2 4]
 [3 1 3]
 [4 2 3]
 [1 3 0]
 [4 1 0]]


In [34]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [35]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [36]:
x = np.random.uniform(0,1,10)
y = np.random.uniform(0,1,10)
print(np.einsum('i->',x))

4.486925110356435


In [37]:
print(np.einsum('i,i->i',x,y))

[0.96008772 0.00543633 0.07281304 0.41550815 0.32379981 0.46979089
 0.02541201 0.21399513 0.31127483 0.24972997]


In [38]:
print(np.einsum('i,i',x,y))
print(np.einsum('i,j->ij',x,y))

3.047847888573379
[[0.96008772 0.12387387 0.548192   0.47782376 0.83682628 0.91331857
  0.09620029 0.4867139  0.42327821 0.90295434]
 [0.04213445 0.00543633 0.02405798 0.02096979 0.03672499 0.04008194
  0.00422185 0.02135995 0.018576   0.03962709]
 [0.12752267 0.01645342 0.07281304 0.06346645 0.11115059 0.1213106
  0.01277771 0.06464728 0.05622149 0.11993398]
 [0.83487742 0.1077188  0.47669928 0.41550815 0.72769118 0.79420769
  0.08365429 0.42323888 0.36807618 0.78519512]
 [0.37149433 0.0479315  0.21211626 0.18488813 0.32379981 0.35339757
  0.03722354 0.18832806 0.16378238 0.34938726]
 [0.49384791 0.06371798 0.28197785 0.24578199 0.43044495 0.46979089
  0.0494833  0.25035488 0.21772496 0.46445976]
 [0.25361419 0.03272219 0.14480892 0.12622064 0.22105378 0.24125977
  0.02541201 0.12856903 0.11181203 0.23852199]
 [0.42212498 0.05446404 0.24102541 0.21008637 0.36793021 0.40156183
  0.0422967  0.21399513 0.18610414 0.39700495]
 [0.70603953 0.09109569 0.40313527 0.35138713 0.61539422 0.6716

In [39]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

In [40]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4 
m = np.logical_and.reduce(np.mod(x,1)==0,axis=-1)
m &= (x.sum(axis=-1)==n)
print(x[m])

[[2. 0. 1. 1.]]


In [41]:
x = np.random.randn(100)
n = 1000
idx = np.random.randint(0,x.size,(n,x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means,[2.5,97.5])
print(confint)

[-0.26301235  0.08923362]
