In [1]:
import numpy as np
import pandas as pd
values = pd.Series(['apple','orange','apple','apple']*2)


In [3]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [4]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [5]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [6]:
values = pd.Series([0,1,0,0]*2)
dim = pd.Series(['apple','orange'])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [7]:
dim

0     apple
1    orange
dtype: object

In [8]:
fruits = ['apple','orange','apple','apple']*2
N = len(fruits)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': np.random.randint(3, 15, size=N),
                   'weight': np.random.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])

In [9]:
df

basket_id   fruit  count    weight
0          0   apple      7  3.477791
1          1  orange     13  2.244725
2          2   apple     12  3.615602
3          3   apple     11  1.226568
4          4   apple      6  0.122902
5          5  orange     11  3.003545
6          6   apple      9  2.038874
7          7   apple      6  3.188164

In [10]:
fruit_cat = df['fruit'].astype('category')

In [11]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [12]:
c = fruit_cat.values

In [13]:
type(c)

pandas.core.arrays.categorical.Categorical

In [14]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [15]:
c.codes


array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [16]:
df['fruit'] = df['fruit'].astype('category')
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [17]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [18]:
categories = ['foo','bar','baz']

In [19]:
codes =[0,1,2,0,0,1]

In [20]:
my_cats_2 = pd.Categorical.from_codes(codes,categories)

In [21]:
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [22]:
np.random.seed(12345)
draws = np.random.randn(1000)

In [23]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [24]:
bins = pd.qcut(draws,4)

In [25]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [27]:
bins = pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])
bins

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [28]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [29]:
bins = pd.Series(bins,name='quartile')

In [30]:
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())

In [31]:
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [33]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [34]:
N = 10000000
draws = pd.Series(np.random.randn(N))
labels = pd.Series(['foo','bar','baz','qux']*(N//4))

In [35]:
categories = labels.astype('category')

In [37]:
labels.memory_usage()

80000080

In [38]:
categories.memory_usage()

10000272

In [39]:
s = pd.Series(['a','b','c','d']*2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [40]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [41]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [42]:
actual_categories = ['a','b','c','d','e']
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [43]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): [a, b, c, d, e]

In [44]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [45]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [46]:
cat_s3  = cat_s[cat_s.isin(['a','b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [47]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): [a, b]

In [48]:
df = pd.DataFrame({'key':['a','b','c']*4,'value':np.arange(12)})


In [49]:
df

key  value
0    a      0
1    b      1
2    c      2
3    a      3
4    b      4
5    c      5
6    a      6
7    b      7
8    c      8
9    a      9
10   b     10
11   c     11

In [50]:
g = df.groupby('key').value
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [51]:
g.transform(lambda x:x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [52]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [53]:
g.transform(lambda x: x*2)

0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
11    22
Name: value, dtype: int32

In [54]:
g.transform(lambda x:x.rank(ascending=False))

0     4
1     4
2     4
3     3
4     3
5     3
6     2
7     2
8     2
9     1
10    1
11    1
Name: value, dtype: int32

In [55]:
def normalize(x):
    return (x-x.mean())/x.std()
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [57]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [58]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [59]:
normalized = (df['value']-g.transform('mean'))/g.transform('std')

In [60]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [63]:
N = 15
times = pd.date_range('2017-05-20 00:00',freq='1min',periods=N)
df = pd.DataFrame({'time':times,'value':np.arange(N)})
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [64]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [65]:
df2 = pd.DataFrame({'time':time.repeat(3),'key':np.tile(['a','b','c'],N),'value':np.arange(N*3)})

In [66]:
df2[:6]

key                time  value
0   a 2017-05-20 00:00:00      0
1   b 2017-05-20 00:00:00      1
2   c 2017-05-20 00:00:00      2
3   a 2017-05-20 00:01:00      3
4   b 2017-05-20 00:01:00      4
5   c 2017-05-20 00:01:00      5

In [67]:
time_key = pd.TimeGrouper('5min')
resampled = (df2.set_index('time').groupby(['key',time_key]).sum())
resampled

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  if __name__ == '__main__':


value
key time                      
a   2017-05-20 00:00:00     30
    2017-05-20 00:05:00    105
    2017-05-20 00:10:00    180
b   2017-05-20 00:00:00     35
    2017-05-20 00:05:00    110
    2017-05-20 00:10:00    185
c   2017-05-20 00:00:00     40
    2017-05-20 00:05:00    115
    2017-05-20 00:10:00    190

In [68]:
resampled.reset_index()

key                time  value
0   a 2017-05-20 00:00:00     30
1   a 2017-05-20 00:05:00    105
2   a 2017-05-20 00:10:00    180
3   b 2017-05-20 00:00:00     35
4   b 2017-05-20 00:05:00    110
5   b 2017-05-20 00:10:00    185
6   c 2017-05-20 00:00:00     40
7   c 2017-05-20 00:05:00    115
8   c 2017-05-20 00:10:00    190

In [69]:
df = load_data()

NameError: name 'load_data' is not defined