In [3]:
import numpy as np
import pandas as pd
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0]=None

In [7]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
from numpy import nan as NA
data= pd.Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1,6.5,3],[1,NA,NA],[NA,NA,NA],[NA,6.5,3]])
cleaned = data.dropna()

In [11]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
cleaned


0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data[4]=NA

In [15]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [16]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1]=NA
df.iloc[:2,2]=NA
df

0         1         2
0 -0.646214       NaN       NaN
1  0.929108       NaN       NaN
2  0.482980       NaN -1.623936
3 -0.085156       NaN -0.029973
4  0.187994  0.810690 -0.802409
5  2.310684  1.287564 -1.692543
6 -0.460245  0.158066 -0.366414

In [18]:
df.dropna()

0         1         2
4  0.187994  0.810690 -0.802409
5  2.310684  1.287564 -1.692543
6 -0.460245  0.158066 -0.366414

In [19]:
df.dropna(thresh=2)

0         1         2
2  0.482980       NaN -1.623936
3 -0.085156       NaN -0.029973
4  0.187994  0.810690 -0.802409
5  2.310684  1.287564 -1.692543
6 -0.460245  0.158066 -0.366414

In [20]:
df.fillna(0)

0         1         2
0 -0.646214  0.000000  0.000000
1  0.929108  0.000000  0.000000
2  0.482980  0.000000 -1.623936
3 -0.085156  0.000000 -0.029973
4  0.187994  0.810690 -0.802409
5  2.310684  1.287564 -1.692543
6 -0.460245  0.158066 -0.366414

In [21]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.646214  0.500000  0.000000
1  0.929108  0.500000  0.000000
2  0.482980  0.500000 -1.623936
3 -0.085156  0.500000 -0.029973
4  0.187994  0.810690 -0.802409
5  2.310684  1.287564 -1.692543
6 -0.460245  0.158066 -0.366414

In [22]:
_ = df.fillna(0,inplace=True)
df

0         1         2
0 -0.646214  0.000000  0.000000
1  0.929108  0.000000  0.000000
2  0.482980  0.000000 -1.623936
3 -0.085156  0.000000 -0.029973
4  0.187994  0.810690 -0.802409
5  2.310684  1.287564 -1.692543
6 -0.460245  0.158066 -0.366414

In [23]:
df.df = pd.DataFrame(np.random.randn(6,3))

In [24]:
df.iloc[2:,1]=NA
df.iloc[4:,2]=NA
df

0    1         2
0 -0.646214  0.0  0.000000
1  0.929108  0.0  0.000000
2  0.482980  NaN -1.623936
3 -0.085156  NaN -0.029973
4  0.187994  NaN       NaN
5  2.310684  NaN       NaN
6 -0.460245  NaN       NaN

In [25]:
df.fillna(method='ffill')

0    1         2
0 -0.646214  0.0  0.000000
1  0.929108  0.0  0.000000
2  0.482980  0.0 -1.623936
3 -0.085156  0.0 -0.029973
4  0.187994  0.0 -0.029973
5  2.310684  0.0 -0.029973
6 -0.460245  0.0 -0.029973

In [26]:
df.fillna(method='ffill',limit=2)

0    1         2
0 -0.646214  0.0  0.000000
1  0.929108  0.0  0.000000
2  0.482980  0.0 -1.623936
3 -0.085156  0.0 -0.029973
4  0.187994  NaN -0.029973
5  2.310684  NaN -0.029973
6 -0.460245  NaN       NaN

In [27]:
data = pd.Series([1,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [28]:
data = pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})

In [29]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [30]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [31]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [32]:
data['v1']=range(7)

In [33]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [34]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [35]:
data.drop_duplicates(['k1','k2'],keep='last')


k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [38]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],'ounces':[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [39]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [40]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [41]:
data ['animal']=lowercased.map(meat_to_animal)

In [42]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [43]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [44]:
data = pd.Series([1,-999,2,-999,-1000,3])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [45]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [47]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [48]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [49]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [50]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['Ohio','Colorado','New York'],
                   columns=['one','two','three','four'])

In [51]:
transform = lambda x:x[:4].upper()

In [52]:
data.index.map(transform)

array(['OHIO', 'COLO', 'NEW '], dtype=object)

In [53]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [54]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [56]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})


one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [57]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [58]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)

In [59]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [60]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [61]:
cats.categories

Index(['(18, 25]', '(25, 35]', '(35, 60]', '(60, 100]'], dtype='object')

In [62]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [63]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [64]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, object): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [65]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [66]:
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [67]:
data = np.random.rand(20)
pd.cut(data,4,precision=2)

[(0.49, 0.72], (0.72, 0.94], (0.26, 0.49], (0.035, 0.26], (0.72, 0.94], ..., (0.72, 0.94], (0.49, 0.72], (0.72, 0.94], (0.26, 0.49], (0.26, 0.49]]
Length: 20
Categories (4, object): [(0.035, 0.26] < (0.26, 0.49] < (0.49, 0.72] < (0.72, 0.94]]

In [68]:
data = np.random.randn(1000)
cats = pd.qcut(data,4)
cats

[[-3.718, -0.627], [-3.718, -0.627], (0.0854, 0.741], (0.741, 2.82], (0.0854, 0.741], ..., (-0.627, 0.0854], (0.741, 2.82], (-0.627, 0.0854], [-3.718, -0.627], [-3.718, -0.627]]
Length: 1000
Categories (4, object): [[-3.718, -0.627] < (-0.627, 0.0854] < (0.0854, 0.741] < (0.741, 2.82]]

In [69]:
pd.value_counts(cats)

(0.741, 2.82]       250
(0.0854, 0.741]     250
(-0.627, 0.0854]    250
[-3.718, -0.627]    250
dtype: int64

In [70]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(-1.25, 0.0854], [-3.718, -1.25], (0.0854, 1.359], (0.0854, 1.359], (0.0854, 1.359], ..., (-1.25, 0.0854], (0.0854, 1.359], (-1.25, 0.0854], [-3.718, -1.25], [-3.718, -1.25]]
Length: 1000
Categories (4, object): [[-3.718, -1.25] < (-1.25, 0.0854] < (0.0854, 1.359] < (1.359, 2.82]]

In [71]:
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()
col = data[2]
col[np.abs(col)>3]

759    3.214513
781   -3.226838
782   -3.017615
897   -3.278108
Name: 2, dtype: float64

In [72]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler = np.random.permutation(5)

In [73]:
sampler

array([2, 1, 0, 3, 4])

In [74]:
df



0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [75]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15
4  16  17  18  19

In [76]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11

In [78]:
choices = pd.Series([5,7,-1,6,4])
draws = choices.sample(n=10,replace=True)
draws

1    7
1    7
1    7
4    4
2   -1
2   -1
3    6
4    4
4    4
4    4
dtype: int64

In [79]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'data1':range(6)})
pd.get_dummies(df['key'])


a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [80]:
dummies = pd.get_dummies(df['key'],prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [1]:
import numpy as np
import pandas as pd
mnames = ['movie_id','title','genres']
movies = pd.read_table('I:\数据分析\pydata-book-2nd-edition\datasets\movielens\movies.dat',sep='::',header=None,names=mnames)
movies[:10]


C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [2]:
all_genres=[]
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)


In [83]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [4]:
zero_matrix = np.zeros((len(movies),len(genres)))
dummies = pd.DataFrame(zero_matrix,columns=genres)
# gen = movies.genres[0]


In [5]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [6]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [7]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices]=1


In [8]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [9]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [12]:
np.random.seed(12345)
values = np.random.rand(10)

In [13]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [14]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))


(0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1]
0       0.0         0.0         0.0         0.0       1.0
1       0.0         1.0         0.0         0.0       0.0
2       1.0         0.0         0.0         0.0       0.0
3       0.0         1.0         0.0         0.0       0.0
4       0.0         0.0         1.0         0.0       0.0
5       0.0         0.0         1.0         0.0       0.0
6       0.0         0.0         0.0         0.0       1.0
7       0.0         0.0         0.0         1.0       0.0
8       0.0         0.0         0.0         1.0       0.0
9       0.0         0.0         0.0         1.0       0.0

In [15]:
val = 'a,b,guido'
val.split(',')


['a', 'b', 'guido']

In [16]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [17]:
first,second,third = pieces
first + '::' + second + '::' +third


'a::b::guido'

In [18]:
'::'.join(pieces)

'a::b::guido'

In [19]:
'guido' in val

True

In [20]:
val.index(',')

1

In [21]:
val.find(':')


-1

In [22]:
val.replace(',','::')


'a::b::guido'

In [24]:
val.replace(',',' ')


'a b guido'

In [25]:
import re

In [26]:
text = 'foo bar\t baz \tqux'
re.split('\s+',text)


['foo', 'bar', 'baz', 'qux']

In [28]:
regex = re.compile('\s+')
regex.split(text)


['foo', 'bar', 'baz', 'qux']

In [29]:
regex.findall(text)


[' ', '\t ', ' \t']

In [30]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern,flags=re.IGNORECASE)


In [31]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""


In [32]:
regex.findall(text)


['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [33]:
m = regex.search(text)
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [34]:
text[m.start():m.end()]

'dave@google.com'

In [35]:
print(regex.match(text))

None


In [36]:
print(regex.sub('REDACTED',text))


Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [37]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern,flags=re.IGNORECASE)

In [38]:
m = regex.match('wesm@bright.net')

In [39]:
m.groups

<function SRE_Match.groups>

In [40]:
m.groups()

('wesm', 'bright', 'net')

In [41]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [42]:
print(regex.sub(r'Username: \1,Domain: \2,Suffix: \3',text))

Dave Username: dave,Domain: google,Suffix: com
Steve Username: steve,Domain: gmail,Suffix: com
Rob Username: rob,Domain: gmail,Suffix: com
Ryan Username: ryan,Domain: yahoo,Suffix: com


In [43]:
data = {'Dava':'dave@google.com','Steve':'steve@gmail.com',
       'Rob':'rob@gmail.co,','Wes':np.nan}
data = pd.Series(data)


In [44]:
data

Dava     dave@google.com
Rob        rob@gmail.co,
Steve    steve@gmail.com
Wes                  NaN
dtype: object

In [45]:
data.isnull()

Dava     False
Rob      False
Steve    False
Wes       True
dtype: bool

In [46]:
data.str.contains('gmail')

Dava     False
Rob       True
Steve     True
Wes        NaN
dtype: object

In [47]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [48]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dava     [(dave, google, com)]
Rob         [(rob, gmail, co)]
Steve    [(steve, gmail, com)]
Wes                        NaN
dtype: object

In [49]:
matches = data.str.match(pattern,flags=re.IGNORECASE)
matches

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: In future versions of pandas, match will change to always return a bool indexer.
  if __name__ == '__main__':


Dava     (dave, google, com)
Rob         (rob, gmail, co)
Steve    (steve, gmail, com)
Wes                      NaN
dtype: object

In [50]:
matches.str.get(1)

Dava     google
Rob       gmail
Steve     gmail
Wes         NaN
dtype: object

In [51]:
matches.str[0]


Dava      dave
Rob        rob
Steve    steve
Wes        NaN
dtype: object

In [52]:
data.str[:5]


Dava     dave@
Rob      rob@g
Steve    steve
Wes        NaN
dtype: object