In [1]:
import pandas as pd
from pandas import Series,DataFrame


In [2]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values


array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj = pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj


d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj['a']
obj['d']=6
obj[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj[obj>0]
obj*2
import numpy as np
np.exp(obj)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [11]:
'b' in obj

True

In [14]:
sdata = {'a':1,'b':2,'c':3,'d':4}
obj3 = pd.Series(sdata)
obj3

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
states=['a','b','c','f']
obj4 = pd.Series(sdata,index=states)
obj4

a    1.0
b    2.0
c    3.0
f    NaN
dtype: float64

In [15]:
pd.isnull(obj4)


a    False
b    False
c    False
f     True
dtype: bool

In [16]:
pd.notnull(obj4)

a     True
b     True
c     True
f    False
dtype: bool

In [17]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
a    1.0
b    2.0
c    3.0
f    NaN
Name: population, dtype: float64

In [20]:
data = {'state':['a','b','c','d'],'year':[1,2,3,4],'pop':[5,6,7,8]}
frame = pd.DataFrame(data)
frame

pop state  year
0    5     a     1
1    6     b     2
2    7     c     3
3    8     d     4

In [16]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [17]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [18]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [19]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                     ....: index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [20]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [21]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [22]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [23]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [24]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [35]:
frame2['debt']=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [37]:
import numpy as np
frame2['debt'] = np.arange(6)

In [38]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt']=val

In [39]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [40]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False

In [41]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [25]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [43]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [44]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [45]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [46]:
obj2.index is labels


True

In [49]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [50]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2 

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [51]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [53]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [54]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],
                    columns = ['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [55]:
obj = pd.Series(np.arange(5),index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [56]:
new_obj = obj.drop('c')

In [57]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [26]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [27]:
index[1:]

Index(['b', 'c'], dtype='object')

In [28]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [29]:
labels = pd.Index(np.arange(3))

In [30]:
labels


Int64Index([0, 1, 2], dtype='int64')

In [31]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [32]:
obj2.index is labels

True

In [33]:
pop ={'Nevda':{2001:2.4,2002:2.9},'Ohio'}

NameError: name 'frame3' is not defined

In [34]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)

In [35]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [36]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [37]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [38]:
'Ohio' in frame3.columns

True

In [39]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [40]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a    0.0
b    1.0
c    2.0
d    NaN
e    NaN
dtype: float64

In [42]:
obj3 = pd.Series(['blue','pueple','yellow'],index=[0,2,4])
obj3

0      blue
2    pueple
4    yellow
dtype: object

In [43]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    pueple
3    pueple
4    yellow
5    yellow
dtype: object

In [45]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame 

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [46]:
frame2 = frame.reindex(['a','b','c','d'])

In [47]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [48]:
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [50]:
obj = pd.Series(np.arange(5),index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [51]:
new_obj = obj.drop('c')

In [52]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [53]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','NewYork'],
                   columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [54]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

In [55]:
data.drop(['two','four'],axis='columns')


one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NewYork    12     14

In [56]:
obj.drop('c',inplace=True)

In [57]:
obj

a    0
b    1
d    3
e    4
dtype: int32

In [58]:
obj = pd.Series(np.arange(4),index=['a','b','c','d'])

In [59]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [60]:
obj[2:4]

c    2
d    3
dtype: int32

In [61]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int32

In [62]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [63]:
obj['b':'c']

b    1
c    2
dtype: int32

In [64]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','NewYork'],
                   columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [65]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int32

In [66]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NewYork      14   12

In [67]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [68]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [69]:
data <5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [70]:
data[data<5]=0

In [71]:
data


one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [72]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [73]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [74]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [75]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [76]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
NewYork    12   13     14

In [77]:
sre = pd.Series(np.arange(3))

In [78]:
ser = sre


In [79]:
ser

0    0
1    1
2    2
dtype: int32

In [80]:
ser[-1]

KeyError: -1

In [81]:
ser2 = pd.Series(np.arange(3),index=['a','b','c'])

In [82]:
ser2[-1]

2

In [83]:
ser2


a    0
b    1
c    2
dtype: int32

In [84]:
ser[:1]

0    0
dtype: int32

In [85]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [86]:
ser.iloc[:1]

0    0
dtype: int32

In [87]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [88]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [89]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [90]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [91]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [92]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [93]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [94]:
df2 = pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [95]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [96]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [97]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [100]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})
df1


A
0  1
1  2

In [101]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [103]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)),columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))

In [104]:
df2.loc[1,'b']=np.nan

In [105]:
df1


a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [106]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [107]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [108]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [109]:
arr = np.arange(12).reshape((3,4))

In [110]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
arr[0]

array([0, 1, 2, 3])

In [112]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [113]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [114]:
series = frame.iloc[0]

In [116]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [117]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [118]:
frame-series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [3]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    0.025681  1.309554  1.823382
Ohio   -1.490966  0.346076 -0.155465
Texas  -0.126287 -1.138547 -0.100754
Oregon -0.280460  0.781920 -1.565028

In [4]:
np.abs(frame)

b         d         e
Utah    0.025681  1.309554  1.823382
Ohio    1.490966  0.346076  0.155465
Texas   0.126287  1.138547  0.100754
Oregon  0.280460  0.781920  1.565028

In [5]:
f = lambda x: x.max()-x.min()
frame.apply(f)

b    1.516647
d    2.448101
e    3.388410
dtype: float64

In [6]:
frame.apply(f,axis='columns')

Utah      1.797701
Ohio      1.837042
Texas     1.037792
Oregon    2.346948
dtype: float64

In [7]:
frame.apply(f,axis='columns')

Utah      1.797701
Ohio      1.837042
Texas     1.037792
Oregon    2.346948
dtype: float64

In [8]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -1.490966 -1.138547 -1.565028
max  0.025681  1.309554  1.823382

In [9]:
format = lambda x:'%.2f' % x

In [10]:
frame.applymap(format)

b      d      e
Utah     0.03   1.31   1.82
Ohio    -1.49   0.35  -0.16
Texas   -0.13  -1.14  -0.10
Oregon  -0.28   0.78  -1.57

In [11]:
frame['e'].map(format)

Utah       1.82
Ohio      -0.16
Texas     -0.10
Oregon    -1.57
Name: e, dtype: object

In [12]:
obj = pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [13]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [14]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [15]:
obj = pd.Series([4,7,-3,2])

In [16]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [17]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [18]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [19]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [20]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [21]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [23]:
obj = pd.Series([7,-5,7,4,2,0,4])
print(obj)
obj.rank()

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64


0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [24]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [25]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [26]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [27]:
frame.rank(axis='columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [29]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [30]:
obj.index.is_unique

False

In [31]:
obj['c']

4

In [32]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
df

0         1         2
a -1.534540 -1.090812 -1.304666
a  0.843501  2.738427  1.277535
b  1.399934  2.408786  0.635866
b -0.515182  0.214971 -0.604805

In [34]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [35]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [36]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [37]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [38]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [39]:
df.idxmax()

one    b
two    d
dtype: object

In [40]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [41]:
df.describe()

C:\Program Files\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3652: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)


one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%         NaN       NaN
50%         NaN       NaN
75%         NaN       NaN
max    7.100000 -1.300000